//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public string id_act { get; set; }
        public System.DateTime Fecha_act { get; set; }
        public System.DateTime Hora_act { get; set; }
        public string Alerta_id_alerta { get; set; }
        public int Contador { get; set; }
    
        public virtual Act_de_mejora Act_de_mejora { get; set; }
        public virtual Asesoria Asesoria { get; set; }
        public virtual Capacitacion Capacitacion { get; set; }
        public virtual Visita Visita { get; set; }
    }
}
