//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int id_emp { get; set; }
        public int Rut_emp { get; set; }
        public string Dv_Rut_emp { get; set; }
        public string Nombre_emp { get; set; }
        public string Direccion_emp { get; set; }
    
        public virtual Gerente Gerente { get; set; }
    }
}
