//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_NMAEntities : DbContext
    {
        public BD_NMAEntities()
            : base("name=BD_NMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Alerta> Alerta { get; set; }
        public virtual DbSet<Checklist> Checklist { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<Gerente> Gerente { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<Profesional> Profesional { get; set; }
        public virtual DbSet<Solicitud> Solicitud { get; set; }
        public virtual DbSet<Accidente> Accidente { get; set; }
        public virtual DbSet<Act_de_mejora> Act_de_mejora { get; set; }
        public virtual DbSet<Asesoria> Asesoria { get; set; }
        public virtual DbSet<Capacitacion> Capacitacion { get; set; }
        public virtual DbSet<Visita> Visita { get; set; }
    }
}
