//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaBD
{
    using System;
    using System.Collections.Generic;
    using PropertyChanged;

    [AddINotifyPropertyChangedInterface]
    public partial class Pago
    {

        public int id_pago { get; set; }
        public string Estado_pago { get; set; }
        public string Mes_pago { get; set; }
        public decimal Valor_extra { get; set; }
        public decimal Total_a_pagar { get; set; }
        public byte[] Comprobante { get; set; }
        public int Plan_id_plan { get; set; }
    
        public virtual Plan Plan { get; set; }
    }
}
