//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesional()
        {
            this.Administrador = new HashSet<Administrador>();
            this.Accidente = new HashSet<Accidente>();
        }
    
        public string id_prof { get; set; }
        public int Rut_prof { get; set; }
        public string Dv_rut_prof { get; set; }
        public string Nombre_prof { get; set; }
        public string Vigencia_prof { get; set; }
        public string Rendimiento_prof { get; set; }
        public string Estado_prof { get; set; }
        public System.DateTime Fecha_nacimiento_prof { get; set; }
        public string Mail_prof { get; set; }
        public string Asesoria_id_act { get; set; }
        public string Alerta_id_alerta { get; set; }
        public string Visita_id_act { get; set; }
        public int Solicitud_id_solicitud { get; set; }
        public int Checklist_id_checklist { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Administrador> Administrador { get; set; }
        public virtual Checklist Checklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accidente> Accidente { get; set; }
        public virtual Visita Visita { get; set; }
    }
}
